/// Remote Rows Normalization for the mORMot LogView Visual Tool
// - this unit is a part of the Open Source Synopse mORMot framework 2,
// licensed under a MPL/GPL/LGPL three license - see LICENSE.md
unit mormot.tools.logview.remote;

{
  *****************************************************************************

   Normalize Remote TSynLog Rows for the mORMot LogView Tool
    - Rewrite any Received Row into the Single Layout of a TSynLogFileView
    - Unique Thread Numbers per Client Connection

  *****************************************************************************
}

interface

{$I ..\..\mormot.defines.inc}

uses
  sysutils,
  mormot.core.base,
  mormot.core.os,
  mormot.core.unicode,
  mormot.core.text,
  mormot.core.datetime,
  mormot.core.log;

const
  /// the thread number of the rows generated by the viewer itself
  // - TSynLogFile.ThreadName() always names thread 1 "Main Thread"
  REMOTE_VIEWER_THREAD = 1;
  /// the thread numbers are stored as word in TSynLogFile.EventThread[]
  REMOTE_MAX_THREAD = 65535;

type
  /// how a received row was recognized by TRemoteLogNormalizer.Normalize
  TRemoteRowKind = (
    rrkCalendar,
    rrkZoned,
    rrkHighRes,
    rrkText);

  /// rewrite the rows received from remote clients into one single layout
  // - TSynLogFile detects the layout of its rows once, whereas remote clients
  // may use calendar, zoned or high resolution timestamps, with or without a
  // ptIdentifiedInOneFile thread column - see issue #344
  // - output is always a 17 chars calendar timestamp, a 3 chars thread column
  // and the 7 chars level text, as the Banner() row which should come first
  // - thread numbers are unique per client connection: REMOTE_VIEWER_THREAD for
  // the viewer rows, then 2..REMOTE_MAX_THREAD for each (connection, thread)
  // - high resolution timestamps are relative to the log start of the client,
  // which is not transmitted: the receipt time is used instead, and the text is
  // prefixed with the original counter - but for sllEnter, to keep the
  // profiling by method name
  // - an unrecognized row is kept as sllInfo text of its connection
  // - this class is not thread-safe: use it from a single thread only
  TRemoteLogNormalizer = class
  protected
    fKeys: TRawUtf8DynArray; // 'connection:thread' of thread 2,3,4...
    fKeysCount: integer;
    fLastConnection: Int64; // most rows come from the same thread in a row
    fLastOrig, fLastThread: cardinal;
    fNames: TRawUtf8DynArray; // [thread - 2] = latest name of this thread
    function ThreadFor(aConnection: Int64; aThread: cardinal;
      out aIsNew: boolean): cardinal;
    procedure SetName(aThread: cardinal; const aName: RawUtf8);
  public
    /// return a 17 chars calendar timestamp of the current UTC time
    // - UTC as TSynLog by default, i.e. unless TSynLogFamily.LocalTimestamp
    class function NowStamp: RawUtf8;
    /// return a row of the viewer itself, with the current UTC time
    class function Banner(const aText: RawUtf8): RawUtf8;
    /// normalize one received row, appending one or several rows to aRows[]
    // - aReceived is the NowStamp value when the row was received
    // - aConnection and aRemoteIP identify the sender connection
    // - returns how the row was recognized
    function Normalize(const aRow, aReceived: RawUtf8; aConnection: Int64;
      const aRemoteIP: RawUtf8; var aRows: TRawUtf8DynArray;
      var aRowsCount: integer): TRemoteRowKind;
    /// forget all known connections and threads, e.g. when the list is cleared
    procedure Clear;
    /// the latest name of a thread number returned by Normalize()
    // - TSynLogFile.ThreadName() orders the SetThreadName rows by memory address,
    // which is no chronological order for rows appended by AddInMemoryLine()
    function ThreadName(aThread: cardinal): RawUtf8;
  end;


implementation

function IsDigits(p: PUtf8Char; n: PtrInt): boolean;
begin
  result := false;
  while n > 0 do
  begin
    if not (p^ in ['0'..'9']) then
      exit;
    inc(p);
    dec(n);
  end;
  result := true;
end;

function IsHex(p: PUtf8Char; n: PtrInt): boolean;
begin // mORMot 2 writes lowercase, but mORMot 1 uppercase hexadecimal
  result := false;
  while n > 0 do
  begin
    if not (p^ in ['0'..'9', 'a'..'f', 'A'..'F']) then
      exit;
    inc(p);
    dec(n);
  end;
  result := true;
end;

function IsThreadChars(p: PUtf8Char): boolean;
begin // Int18ToText() writes 3 chars of $20 + 6-bit values
  result := (p[0] in [#32..#95]) and
            (p[1] in [#32..#95]) and
            (p[2] in [#32..#95]);
end;

function FindLevel(p: PUtf8Char; out aLevel: TSynLogLevel): boolean;
var
  l: TSynLogLevel;
begin
  // no ambiguity with a thread column: every level text starts with a space
  // and has no 4 spaces at its start, so 3 thread chars + level can't match
  for l := succ(sllNone) to high(l) do
    if CompareMem(p, @LOG_LEVEL_TEXT[l][1], 7) then
    begin
      aLevel := l;
      result := true;
      exit;
    end;
  result := false;
end;

function LevelText(aLevel: TSynLogLevel): RawUtf8;
begin
  FastSetString(result, @LOG_LEVEL_TEXT[aLevel][1], 7);
end;


{ TRemoteLogNormalizer }

class function TRemoteLogNormalizer.NowStamp: RawUtf8;
var
  st: TSynSystemTime;
begin
  st.FromNowUtc; // as TSynLog rows, unless TSynLogFamily.LocalTimestamp is set
  FastSetString(result, 17);
  st.ToLogTime(pointer(result));
end;

class function TRemoteLogNormalizer.Banner(const aText: RawUtf8): RawUtf8;
begin
  result := NowStamp + Int18ToChars3(REMOTE_VIEWER_THREAD) +
    LevelText(sllInfo) + aText;
end;

function TRemoteLogNormalizer.ThreadFor(aConnection: Int64; aThread: cardinal;
  out aIsNew: boolean): cardinal;
var
  key: RawUtf8;
  i: PtrInt;
begin
  aIsNew := false;
  result := fLastThread;
  if (result <> 0) and
     (aConnection = fLastConnection) and
     (aThread = fLastOrig) then
    exit; // no key allocation nor search
  FormatUtf8('%:%', [aConnection, aThread], key);
  result := 0;
  for i := 0 to fKeysCount - 1 do
    if fKeys[i] = key then
    begin
      result := i + 2; // 1 = REMOTE_VIEWER_THREAD
      break;
    end;
  if result = 0 then
    if fKeysCount + 2 >= REMOTE_MAX_THREAD then
      result := REMOTE_MAX_THREAD // shared overflow thread
    else
    begin
      AddRawUtf8(fKeys, fKeysCount, key);
      result := fKeysCount + 1;
      aIsNew := true;
    end;
  fLastConnection := aConnection;
  fLastOrig := aThread;
  fLastThread := result;
end;

function TRemoteLogNormalizer.Normalize(const aRow, aReceived: RawUtf8;
  aConnection: Int64; const aRemoteIP: RawUtf8; var aRows: TRawUtf8DynArray;
  var aRowsCount: integer): TRemoteRowKind;
var
  p: PUtf8Char;
  len, ofs, tabs: PtrInt;
  level: TSynLogLevel;
  orig, thread: cardinal;
  isnew, isname: boolean;
  stamp, payload, sender, row: RawUtf8;
begin
  p := pointer(aRow);
  len := length(aRow);
  result := rrkText;
  ofs := 0;
  // recognize the timestamp
  if (len >= 17 + 7) and
     IsDigits(p, 8) and
     (p[8] = ' ') and
     IsDigits(p + 9, 8) then
    if p[17] = 'Z' then
    begin
      result := rrkZoned;
      ofs := 18;
    end
    else
    begin
      result := rrkCalendar;
      ofs := 17;
    end
  else if (len >= 16 + 7) and
          IsHex(p, 16) then
  begin
    result := rrkHighRes;
    ofs := 16;
  end;
  // recognize the optional thread column and the level text
  orig := 0;
  level := sllInfo;
  if result <> rrkText then
    if FindLevel(p + ofs, level) then
      // no thread column
    else if (len >= ofs + 3 + 7) and
            IsThreadChars(p + ofs) and
            FindLevel(p + ofs + 3, level) then
    begin
      orig := Chars3ToInt18(p + ofs);
      inc(ofs, 3);
    end
    else
      result := rrkText;
  // compute the new timestamp and text
  case result of
    rrkCalendar,
    rrkZoned:
      FastSetString(stamp, p, 17); // the 'Z' marker is not part of the layout
  else
    stamp := aReceived;
  end;
  if result = rrkText then
  begin
    level := sllInfo;
    payload := aRow;
  end
  else
    payload := copy(aRow, ofs + 8, MaxInt);
  // TSynLogFile.ProcessOneLine() expects "SetThreadName " right after the level
  isname := (level = sllInfo) and
            (result <> rrkText) and
            IdemPChar(pointer(payload), 'SETTHREADNAME ');
  if (result = rrkHighRes) and
     (level <> sllEnter) and // keep the profiling by method name
     not isname then
  begin
    tabs := 1; // keep the recursion indentation before the marker
    while (tabs <= length(payload)) and
          (payload[tabs] = #9) do
      inc(tabs);
    insert(FormatUtf8('[hires %] ', [copy(aRow, 1, 16)]), payload, tabs);
  end;
  // make the thread unique, and name it after its sender
  if aRemoteIP = '' then
    FormatUtf8('local #%', [aConnection], sender) // e.g. from 127.0.0.1
  else
    FormatUtf8('% #%', [aRemoteIP, aConnection], sender);
  thread := ThreadFor(aConnection, orig, isnew);
  if isnew and
     not isname then
  begin
    // TSynLogFile.ThreadName() expects "SetThreadName ...=name" after column 40
    if orig = 0 then
      row := sender + ' no thread column'
    else
      FormatUtf8('% thread %', [sender, orig], row);
    SetName(thread, row);
    AddRawUtf8(aRows, aRowsCount, FormatUtf8('%%%SetThreadName 0 0=%',
      [stamp, Int18ToChars3(thread), LevelText(sllInfo), row]));
  end;
  if isname then
  begin
    ofs := PosExChar('=', payload);
    if ofs > 0 then
    begin
      insert(sender + ' ', payload, ofs + 1);
      SetName(thread, copy(payload, ofs + 1, MaxInt));
    end;
  end;
  row := stamp + Int18ToChars3(thread) + LevelText(level) + payload;
  AddRawUtf8(aRows, aRowsCount, row);
end;

procedure TRemoteLogNormalizer.SetName(aThread: cardinal; const aName: RawUtf8);
begin
  if (aThread < 2) or
     (aThread >= REMOTE_MAX_THREAD) then
    exit; // viewer rows or shared overflow thread
  if PtrInt(aThread - 2) >= length(fNames) then
    SetLength(fNames, NextGrow(aThread));
  fNames[aThread - 2] := aName;
end;

function TRemoteLogNormalizer.ThreadName(aThread: cardinal): RawUtf8;
begin
  if aThread = REMOTE_VIEWER_THREAD then
    result := 'LogView'
  else if aThread = REMOTE_MAX_THREAD then
    result := 'overflow: too many remote threads'
  else if (aThread >= 2) and
          (PtrInt(aThread - 2) < length(fNames)) then
    result := fNames[aThread - 2]
  else
    result := '';
end;

procedure TRemoteLogNormalizer.Clear;
begin
  fKeys := nil;
  fKeysCount := 0;
  fNames := nil;
  fLastThread := 0;
end;


end.
